### ISSUE TITLE
Issue Creating New Accounts 

### ISSUE THREAD

**Issue by kknee** [glos/myglos#28] opened 2016-07-14 18:40 UTC
User reports that nothing happens when the submit button is clicked.

![image](https://cloud.githubusercontent.com/assets/196868/16851295/ed2a4208-49d0-11e6-9f8d-0433bd7d9dae.png)

**Comment by kkoch** [comment] 2016-07-14 20:50
1) @tslawecki gets the following when using Chrome >
I get the following in Chrome when I press Create an Account ...

catalog.js:3 GET http://portal.glos.us/api/user/self 401 (UNAUTHORIZED)send @ catalog.js:3ajax @ catalog.js:3b.ajax @ catalog.js:12b.sync @ catalog.js:12sync @ catalog.js:12fetch @ catalog.js:12fetchModels @ catalog.js:41start @ catalog.js:42(anonymous function) @ (index):192j @ catalog.js:1fireWith @ catalog.js:1ready @ catalog.js:1I @ catalog.js:1

 catalog.js:3 GET http://portal.glos.us/api/map 401 (UNAUTHORIZED)send @ catalog.js:3ajax @ catalog.js:3b.ajax @ catalog.js:12b.sync @ catalog.js:12sync @ catalog.js:12fetch @ catalog.js:12fetchCollections @ catalog.js:41start @ catalog.js:42(anonymous function) @ (index):192j @ catalog.js:1fireWith @ catalog.js:1ready @ catalog.js:1I @ catalog.js:1

 catalog.js:3 GET http://portal.glos.us/api/alert 401 (UNAUTHORIZED)send @ catalog.js:3ajax @ catalog.js:3b.ajax @ catalog.js:12b.sync @ catalog.js:12sync @ catalog.js:12fetch @ catalog.js:12(anonymous function) @ catalog.js:42o.map.o.collect @ catalog.js:11fetchCollections @ catalog.js:42start @ catalog.js:42(anonymous function) @ (index):192j @ catalog.js:1fireWith @ catalog.js:1ready @ catalog.js:1I @ catalog.js:1

 data.glos.us/metadata/srv/eng/resources.get?uuid=8d8b77d5-fcad-4ded-9071-a502a099ce68&fname=Wilmette_Buoy_Skyline_sm_s.png:1 GET http://data.glos.us/metadata/srv/eng/resources.get?uuid=8d8b77d5-fcad-4ded-9071-a502a099ce68&fname=Wilmette_Buoy_Skyline_sm_s.png net::ERR_CONNECTION_TIMED_OUT

2) I (@kkoch) tested with firefox and I get no error but it also just sits there on the form page - does not go back to the catalog

**Comment by lukecampbell** [comment] 2016-07-15 12:03
First off I want to thank everyone for including the console! I'll look into this today.

**Comment by lukecampbell** [comment] 2016-07-15 15:10
Fixed

**Comment by kkoch** [comment] 2016-07-15 15:39
Thanks!  Can you put in the comments what the resolution was?

Kathy

**Comment by lukecampbell** [comment] 2016-07-15 16:13
It's extremely hard to describe, and normally I'm all about diving into technical things. But I think it's best to summarize, it was a bug in the code, and I fixed it.

**Comment by lukecampbell** [comment] 2016-07-15 16:15
For developers, the commit sha that corrected it was:
5fa22e7e8217bec49e6101ce1d4d9e546e965c89 in OceansMap.

```
Adds RedisStore Login management
- Patches the existing redis-based user store
- Adds config key USER_ENGINE
- Adds documentaiton
- Adds tests

Note: This is only basic login capabilities, no admin stuff yet
```

**Comment by kkoch** [comment] 2016-10-28 13:45
User (Doug Kane) reports that he is unable to create a myGLOS account:

"....I am having a problem signing up for a MyGLOS account.  When I click on that option in the Data Portal nothing happens.  Please help if you can or send this on to someone who might be able to help.  I am a GLOS member and went to the conference in Toledo."

We have had him try again and this is his reponse: "Just tried in Google Chrome, Internet Explorer, and Firefox.  Did not work no matter which way I got to the site."  He is running Windows 10.

**Comment by kkoch** [comment] 2016-10-28 13:46
Asked @lukecampbell to create an account for him while we investigate further.

Doug Kane dkane@defiance.edu

**Comment by kkoch** [comment] 2016-10-28 14:55
Doug reports that he was able to create an account.   

Kelli Knee reports that the issue is with click speed so closing this issue again and putting that under the other issue tracker for click speed.

**Closed as completed by kkoch** 2016-10-28 14:55 UTC
Labels: bug
